"""
molecules_extended.py — Extended molecular benchmark (auto-generated).

Generated by extend_database.py, 142 new molecules.
Sources: NIST Chemistry WebBook, ATcT v1.130.
All D_at values in eV.
"""

MOLECULES_EXT = {
    'HOBr': {'smiles': 'BrO', 'D_at': 6.582, 'source': 'ATcT'},  # BrHO ΔHf=-56.0
    'HOCl': {'smiles': 'ClO', 'D_at': 6.871, 'source': 'ATcT'},  # ClHO ΔHf=-74.5
    # ClO2 removed: radical species (odd electron count)
    'ClNO': {'smiles': 'ClN=O', 'D_at': 8.203, 'source': 'NIST'},  # ClNO ΔHf=51.7
    'SOCl2': {'smiles': 'ClS(Cl)=O', 'D_at': 10.172, 'source': 'NIST'},  # Cl2OS ΔHf=-212.5
    'carbonyl_sulfide': {'smiles': 'C(=O)=S', 'D_at': 14.318, 'source': 'NIST'},  # COS ΔHf=-138.4
    'thioformaldehyde': {'smiles': 'C=S', 'D_at': 14.694, 'source': 'NIST'},  # CH2S ΔHf=12.1
    'COCl2': {'smiles': 'ClC(Cl)=O', 'D_at': 14.793, 'source': 'NIST'},  # CCl2O ΔHf=-218.8
    'dioxirane': {'smiles': 'C1OO1', 'D_at': 17.157, 'source': 'ATcT'},  # CH2O2 ΔHf=-4.4
    'HNCO': {'smiles': 'N=C=O', 'D_at': 18.433, 'source': 'ATcT'},  # CHNO ΔHf=-122.0
    'HOCN': {'smiles': 'OC#N', 'D_at': 18.817, 'source': 'NIST'},  # CHNO ΔHf=-159.0
    'vinyl_fluoride': {'smiles': 'C=CF', 'D_at': 23.895, 'source': 'NIST'},  # C2H3F ΔHf=-138.8
    '1,1,1-trichloroethane': {'smiles': 'CC(Cl)(Cl)Cl', 'D_at': 26.902, 'source': 'NIST'},  # C2H3Cl3 ΔHf=-144.4
    '1,1-dichloroethane': {'smiles': 'CC(Cl)Cl', 'D_at': 27.731, 'source': 'NIST'},  # C2H4Cl2 ΔHf=-127.7
    '1,2-dichloroethane': {'smiles': 'C(CCl)Cl', 'D_at': 27.753, 'source': 'NIST'},  # C2H4Cl2 ΔHf=-129.8
    'cyclopropene': {'smiles': 'C1C=C1', 'D_at': 28.449, 'source': 'NIST'},  # C3H4 ΔHf=277.1
    'methyl_isocyanate': {'smiles': 'CN=C=O', 'D_at': 30.069, 'source': 'NIST'},  # C2H3NO ΔHf=-92.0
    'dimethylsilane': {'smiles': 'C[SiH2]C', 'D_at': 34.061, 'source': 'NIST'},  # C2H6Si ΔHf=-95.0
    'malononitrile': {'smiles': 'C(C#N)C#N', 'D_at': 34.671, 'source': 'NIST'},  # C3H2N2 ΔHf=186.2
    'N-methylformamide': {'smiles': 'CNC=O', 'D_at': 35.614, 'source': 'NIST'},  # C2H5NO ΔHf=-191.0
    'trifluoroethanol': {'smiles': 'C(C(F)(F)F)O', 'D_at': 35.892, 'source': 'NIST'},  # C2H3F3O ΔHf=-888.4
    'nitroethane': {'smiles': 'CC[N+](=O)[O-]', 'D_at': 37.277, 'source': 'NIST'},  # C2H5NO2 ΔHf=-102.3
    'oxalic_acid': {'smiles': 'C(=O)(C(=O)O)O', 'D_at': 37.289, 'source': 'NIST'},  # C2H2O4 ΔHf=-731.8
    'glycolic_acid': {'smiles': 'C(C(=O)O)O', 'D_at': 37.689, 'source': 'NIST'},  # C2H4O3 ΔHf=-583.5
    'methyl_vinyl_ether': {'smiles': 'COC=C', 'D_at': 39.501, 'source': 'NIST'},  # C3H6O ΔHf=-104.0
    'allyl_alcohol': {'smiles': 'C=CCO', 'D_at': 39.713, 'source': 'NIST'},  # C3H6O ΔHf=-124.5
    'imidazole': {'smiles': 'C1=CN=CN1', 'D_at': 39.742, 'source': 'NIST'},  # C3H4N2 ΔHf=132.9
    'acrylic_acid': {'smiles': 'C=CC(=O)O', 'D_at': 39.907, 'source': 'NIST'},  # C3H4O2 ΔHf=-330.0
    '1,2-dichloropropane': {'smiles': 'CC(CCl)Cl', 'D_at': 40.050, 'source': 'NIST'},  # C3H6Cl2 ΔHf=-163.6
    'dimethyl_sulfone': {'smiles': 'CS(=O)(=O)C', 'D_at': 40.317, 'source': 'NIST'},  # C2H6O2S ΔHf=-373.1
    'methylenecyclopropane': {'smiles': 'C=C1CC1', 'D_at': 41.133, 'source': 'NIST'},  # C4H6 ΔHf=206.0
    '1-butyne': {'smiles': 'CCC#C', 'D_at': 41.556, 'source': 'NIST'},  # C4H6 ΔHf=165.2
    '1,3-dioxolane': {'smiles': 'C1COCO1', 'D_at': 44.462, 'source': 'NIST'},  # C3H6O2 ΔHf=-333.5
    'ethyl_formate': {'smiles': 'CCOC=O', 'D_at': 44.855, 'source': 'NIST'},  # C3H6O2 ΔHf=-371.4
    'methyl_acetate': {'smiles': 'CC(=O)OC', 'D_at': 45.289, 'source': 'NIST'},  # C3H6O2 ΔHf=-413.3
    'divinyl_ether': {'smiles': 'C=COC=C', 'D_at': 46.194, 'source': 'NIST'},  # C4H6O ΔHf=-33.1
    'pyrazine': {'smiles': 'C1=CN=CC=N1', 'D_at': 46.515, 'source': 'NIST'},  # C4H4N2 ΔHf=196.1
    'pyrimidine': {'smiles': 'C1=CN=CN=C1', 'D_at': 46.518, 'source': 'NIST'},  # C4H4N2 ΔHf=195.8
    'crotonaldehyde': {'smiles': 'CC=CC=O', 'D_at': 46.915, 'source': 'NIST'},  # C4H6O ΔHf=-102.7
    'succinonitrile': {'smiles': 'C(CC#N)C#N', 'D_at': 47.099, 'source': 'NIST'},  # C4H4N2 ΔHf=139.7
    '2-butene_trans': {'smiles': 'CC=CC', 'D_at': 47.903, 'source': 'NIST'},  # C4H8 ΔHf=-11.2
    'dimethyl_phosphite': {'smiles': 'COP(=O)OC', 'D_at': 49.069, 'source': 'NIST'},  # C2H7O3P ΔHf=-711.0
    'malonic_acid': {'smiles': 'C(C(=O)O)C(=O)O', 'D_at': 49.329, 'source': 'NIST'},  # C3H4O4 ΔHf=-740.8
    '2-methoxyethanol': {'smiles': 'COCCO', 'D_at': 49.430, 'source': 'NIST'},  # C3H8O2 ΔHf=-376.9
    'lactic_acid': {'smiles': 'CC(C(=O)O)O', 'D_at': 49.635, 'source': 'NIST'},  # C3H6O3 ΔHf=-583.5
    'trimethylsilane': {'smiles': 'C[SiH](C)C', 'D_at': 51.231, 'source': 'NIST'},  # C3H10Si ΔHf=-163.0
    'ethyl_vinyl_ether': {'smiles': 'CCOC=C', 'D_at': 51.822, 'source': 'NIST'},  # C4H8O ΔHf=-140.2
    'methyl_acrylate': {'smiles': 'COC(=O)C=C', 'D_at': 51.884, 'source': 'NIST'},  # C4H6O2 ΔHf=-333.0
    'vinyl_acetate': {'smiles': 'CC(=O)OC=C', 'D_at': 52.052, 'source': 'NIST'},  # C4H6O2 ΔHf=-349.2
    'gamma-butyrolactone': {'smiles': 'C1CC(=O)OC1', 'D_at': 52.216, 'source': 'NIST'},  # C4H6O2 ΔHf=-365.0
    '2-methylthiophene': {'smiles': 'CC1=CC=CS1', 'D_at': 52.703, 'source': 'NIST'},  # C5H6S ΔHf=83.5
    '2-butanone': {'smiles': 'CCC(=O)C', 'D_at': 52.846, 'source': 'NIST'},  # C4H8O ΔHf=-239.0
    '1-pentyne': {'smiles': 'CCCC#C', 'D_at': 53.719, 'source': 'NIST'},  # C5H8 ΔHf=144.3
    '2-methylfuran': {'smiles': 'CC1=CC=CO1', 'D_at': 53.924, 'source': 'NIST'},  # C5H6O ΔHf=-62.3
    'isoprene': {'smiles': 'CC(=C)C=C', 'D_at': 54.430, 'source': 'NIST'},  # C5H8 ΔHf=75.7
    'cyclopentene': {'smiles': 'C1CC=CC1', 'D_at': 54.863, 'source': 'NIST'},  # C5H8 ΔHf=33.9
    '1,2-dichlorobenzene': {'smiles': 'C1=CC=C(C(=C1)Cl)Cl', 'D_at': 55.806, 'source': 'NIST'},  # C6H4Cl2 ΔHf=30.2
    'bromobenzene': {'smiles': 'C1=CC=C(C=C1)Br', 'D_at': 55.931, 'source': 'NIST'},  # C6H5Br ΔHf=105.4
    'diethyl_sulfide': {'smiles': 'CCSCC', 'D_at': 56.044, 'source': 'NIST'},  # C4H10S ΔHf=-83.5
    '1,4-dioxane': {'smiles': 'C1COCCO1', 'D_at': 56.220, 'source': 'NIST'},  # C4H8O2 ΔHf=-315.3
    'chlorobenzene': {'smiles': 'C1=CC=C(C=C1)Cl', 'D_at': 56.583, 'source': 'NIST'},  # C6H5Cl ΔHf=52.0
    '1,3-dioxane': {'smiles': 'C1COCOC1', 'D_at': 56.887, 'source': 'NIST'},  # C4H8O2 ΔHf=-379.7
    'methyl_propanoate': {'smiles': 'CCC(=O)OC', 'D_at': 57.471, 'source': 'NIST'},  # C4H8O2 ΔHf=-436.0
    '1-butanol': {'smiles': 'CCCCO', 'D_at': 57.734, 'source': 'NIST'},  # C4H10O ΔHf=-274.6
    'butyric_acid': {'smiles': 'CCCC(=O)O', 'D_at': 57.883, 'source': 'NIST'},  # C4H8O2 ΔHf=-475.8
    'fluorobenzene': {'smiles': 'C1=CC=C(C=C1)F', 'D_at': 57.888, 'source': 'NIST'},  # C6H5F ΔHf=-115.9
    '2-butanol': {'smiles': 'CCC(C)O', 'D_at': 57.923, 'source': 'NIST'},  # C4H10O ΔHf=-292.8
    'morpholine': {'smiles': 'C1COCCN1', 'D_at': 59.232, 'source': 'NIST'},  # C4H9NO ΔHf=-164.4
    'hexafluorobenzene': {'smiles': 'C1(=C(C(=C(C(=C1F)F)F)F)F)F', 'D_at': 59.778, 'source': 'NIST'},  # C6F6 ΔHf=-991.3
    'thiophenol': {'smiles': 'C1=CC=C(C=C1)S', 'D_at': 59.843, 'source': 'NIST'},  # C6H6S ΔHf=111.3
    'N,N-dimethylacetamide': {'smiles': 'CC(=O)N(C)C', 'D_at': 59.860, 'source': 'NIST'},  # C4H9NO ΔHf=-225.0
    '1-pentene': {'smiles': 'CCCC=C', 'D_at': 59.954, 'source': 'NIST'},  # C5H10 ΔHf=-21.3
    'n-butylamine': {'smiles': 'CCCCN', 'D_at': 60.416, 'source': 'NIST'},  # C4H11N ΔHf=-91.9
    '1,3-cyclohexadiene': {'smiles': 'C1CC=CC=C1', 'D_at': 61.544, 'source': 'NIST'},  # C6H8 ΔHf=106.0
    'succinic_acid': {'smiles': 'C(CC(=O)O)C(=O)O', 'D_at': 62.119, 'source': 'NIST'},  # C4H6O4 ΔHf=-822.1
    'piperazine': {'smiles': 'C1CNCCN1', 'D_at': 62.155, 'source': 'NIST'},  # C4H10N2 ΔHf=-5.0
    'tetramethylsilane': {'smiles': 'C[Si](C)(C)C', 'D_at': 63.903, 'source': 'NIST'},  # C4H12Si ΔHf=-233.0
    '3-methylpyridine': {'smiles': 'CC1=CN=CC=C1', 'D_at': 64.179, 'source': 'NIST'},  # C6H7N ΔHf=106.4
    '4-methylpyridine': {'smiles': 'CC1=CC=NC=C1', 'D_at': 64.203, 'source': 'NIST'},  # C6H7N ΔHf=104.1
    '2-methylpyridine': {'smiles': 'CC1=CC=CC=N1', 'D_at': 64.254, 'source': 'NIST'},  # C6H7N ΔHf=99.2
    '3-pentanone': {'smiles': 'CCC(=O)CC', 'D_at': 64.998, 'source': 'NIST'},  # C5H10O ΔHf=-258.8
    'nitrobenzene': {'smiles': 'C1=CC=C(C=C1)[N+](=O)[O-]', 'D_at': 65.229, 'source': 'NIST'},  # C6H5NO2 ΔHf=67.5
    '2-methylbutane': {'smiles': 'CCC(C)C', 'D_at': 65.845, 'source': 'NIST'},  # C5H12 ΔHf=-153.7
    'benzonitrile': {'smiles': 'C1=CC=C(C=C1)C#N', 'D_at': 65.956, 'source': 'NIST'},  # C7H5N ΔHf=215.7
    'hydroquinone': {'smiles': 'C1=CC(=CC=C1O)O', 'D_at': 66.039, 'source': 'NIST'},  # C6H6O2 ΔHf=-265.3
    'catechol': {'smiles': 'C1=CC=C(C(=C1)O)O', 'D_at': 66.114, 'source': 'NIST'},  # C6H6O2 ΔHf=-272.6
    'cyclohexene': {'smiles': 'C1CCC=CC1', 'D_at': 67.206, 'source': 'NIST'},  # C6H10 ΔHf=-4.3
    'benzaldehyde': {'smiles': 'C1=CC=C(C=C1)C=O', 'D_at': 68.515, 'source': 'NIST'},  # C7H6O ΔHf=-36.7
    'propyl_acetate': {'smiles': 'CCCOC(=O)C', 'D_at': 69.739, 'source': 'NIST'},  # C5H10O2 ΔHf=-467.0
    'MTBE': {'smiles': 'CC(C)(C)OC', 'D_at': 69.772, 'source': 'NIST'},  # C5H12O ΔHf=-283.4
    '2-pentanol': {'smiles': 'CCCC(C)O', 'D_at': 70.099, 'source': 'NIST'},  # C5H12O ΔHf=-314.9
    'cyclohexanone': {'smiles': 'C1CCC(=O)CC1', 'D_at': 72.087, 'source': 'NIST'},  # C6H10O ΔHf=-226.1
    '1-hexene': {'smiles': 'CCCCC=C', 'D_at': 72.112, 'source': 'NIST'},  # C6H12 ΔHf=-41.7
    'thioanisole': {'smiles': 'CSC1=CC=CC=C1', 'D_at': 72.383, 'source': 'NIST'},  # C7H8S ΔHf=54.0
    'methylcyclopentane': {'smiles': 'CC1CCCC1', 'D_at': 72.781, 'source': 'NIST'},  # C6H12 ΔHf=-106.2
    'anisole': {'smiles': 'COC1=CC=CC=C1', 'D_at': 73.357, 'source': 'NIST'},  # C7H8O ΔHf=-67.9
    'phenyl_methanol': {'smiles': 'C1=CC=C(C=C1)CO', 'D_at': 73.694, 'source': 'NIST'},  # C7H8O ΔHf=-100.4
    'benzoic_acid': {'smiles': 'C1=CC=C(C=C1)C(=O)O', 'D_at': 73.764, 'source': 'NIST'},  # C7H6O2 ΔHf=-294.0
    'cresol_p': {'smiles': 'CC1=CC=C(C=C1)O', 'D_at': 73.953, 'source': 'NIST'},  # C7H8O ΔHf=-125.4
    'diethyl_carbonate': {'smiles': 'CCOC(=O)OCC', 'D_at': 74.093, 'source': 'NIST'},  # C5H10O3 ΔHf=-637.9
    'benzofuran': {'smiles': 'C1=CC=C2C(=C1)C=CO2', 'D_at': 75.601, 'source': 'NIST'},  # C8H6O ΔHf=-3.8
    'cyclohexanol': {'smiles': 'C1CCC(CC1)O', 'D_at': 77.229, 'source': 'NIST'},  # C6H12O ΔHf=-286.2
    '3-methylpentane': {'smiles': 'CCC(C)CC', 'D_at': 77.983, 'source': 'NIST'},  # C6H14 ΔHf=-172.1
    '2-methylpentane': {'smiles': 'CCCC(C)C', 'D_at': 78.011, 'source': 'NIST'},  # C6H14 ΔHf=-174.8
    '2,2-dimethylbutane': {'smiles': 'CCC(C)(C)C', 'D_at': 78.126, 'source': 'NIST'},  # C6H14 ΔHf=-185.9
    'caprolactam': {'smiles': 'C1CCC(=O)NCC1', 'D_at': 79.182, 'source': 'NIST'},  # C6H11NO ΔHf=-220.0
    'acetophenone': {'smiles': 'CC(=O)C1=CC=CC=C1', 'D_at': 80.979, 'source': 'NIST'},  # C8H8O ΔHf=-86.7
    'ethylbenzene': {'smiles': 'CCC1=CC=CC=C1', 'D_at': 81.708, 'source': 'NIST'},  # C8H10 ΔHf=29.8
    'di-n-propyl_ether': {'smiles': 'CCCOCCC', 'D_at': 81.818, 'source': 'NIST'},  # C6H14O ΔHf=-293.0
    'xylene_o': {'smiles': 'CC1=CC=CC=C1C', 'D_at': 81.819, 'source': 'NIST'},  # C8H10 ΔHf=19.1
    'xylene_p': {'smiles': 'CC1=CC=C(C=C1)C', 'D_at': 81.831, 'source': 'NIST'},  # C8H10 ΔHf=18.0
    'xylene_m': {'smiles': 'CC1=CC(=CC=C1)C', 'D_at': 81.838, 'source': 'NIST'},  # C8H10 ΔHf=17.3
    '1-hexanol': {'smiles': 'CCCCCCO', 'D_at': 82.056, 'source': 'NIST'},  # C6H14O ΔHf=-315.9
    'indene': {'smiles': 'C1C=CC2=CC=CC=C21', 'D_at': 83.261, 'source': 'NIST'},  # C9H8 ΔHf=160.7
    'triethylamine': {'smiles': 'CCN(CC)CC', 'D_at': 84.315, 'source': 'NIST'},  # C6H15N ΔHf=-92.4
    'cycloheptane': {'smiles': 'C1CCCCCC1', 'D_at': 84.851, 'source': 'NIST'},  # C7H14 ΔHf=-118.1
    'diisopropylamine': {'smiles': 'CC(C)NC(C)C', 'D_at': 84.852, 'source': 'NIST'},  # C6H15N ΔHf=-144.2
    'methylcyclohexane': {'smiles': 'CC1CCCCC1', 'D_at': 85.230, 'source': 'NIST'},  # C7H14 ΔHf=-154.7
    'isoquinoline': {'smiles': 'C1=CC=C2C=NC=CC2=C1', 'D_at': 85.445, 'source': 'NIST'},  # C9H7N ΔHf=204.6
    'quinoline': {'smiles': 'C1=CC=C2C(=C1)C=CC=N2', 'D_at': 85.488, 'source': 'NIST'},  # C9H7N ΔHf=200.5
    'methyl_benzoate': {'smiles': 'COC(=O)C1=CC=CC=C1', 'D_at': 85.647, 'source': 'NIST'},  # C8H8O2 ΔHf=-287.9
    'indane': {'smiles': 'C1CC2=CC=CC=C2C1', 'D_at': 89.326, 'source': 'NIST'},  # C9H10 ΔHf=11.5
    'cumene': {'smiles': 'CC(C)C1=CC=CC=C1', 'D_at': 93.922, 'source': 'NIST'},  # C9H12 ΔHf=4.0
    'mesitylene': {'smiles': 'CC1=CC(=CC(=C1)C)C', 'D_at': 94.131, 'source': 'NIST'},  # C9H12 ΔHf=-16.1
    'cyclooctane': {'smiles': 'C1CCCCCCC1', 'D_at': 96.863, 'source': 'NIST'},  # C8H16 ΔHf=-124.4
    'triethyl_phosphate': {'smiles': 'CCOP(=O)(OCC)OCC', 'D_at': 103.656, 'source': 'NIST'},  # C6H15O4P ΔHf=-1118.0
    'biphenyl': {'smiles': 'C1=CC=C(C=C1)C2=CC=CC=C2', 'D_at': 109.842, 'source': 'NIST'},  # C12H10 ΔHf=182.0
    'undecane': {'smiles': 'CCCCCCCCCCC', 'D_at': 138.734, 'source': 'NIST'},  # C11H24 ΔHf=-270.3
    'dodecane': {'smiles': 'CCCCCCCCCCCC', 'D_at': 150.894, 'source': 'NIST'},  # C12H26 ΔHf=-290.9
}


# ── Batch 2: more_molecules.py (auto-generated) ──
MOLECULES_EXT.update({
    'Cl2O': {'smiles': 'ClOCl', 'D_at': 4.265, 'source': 'NIST'},  # Cl2O ΔHf=80.3
    'KF': {'smiles': '[K]F', 'D_at': 5.144, 'source': 'NIST'},  # FK ΔHf=-327.9
    'SCl2': {'smiles': 'ClSCl', 'D_at': 5.569, 'source': 'NIST'},  # Cl2S ΔHf=-17.6
    'SOF2': {'smiles': 'FS(=O)F', 'D_at': 12.738, 'source': 'NIST'},  # F2OS ΔHf=-543.9
    'NH2OH': {'smiles': 'NO', 'D_at': 14.706, 'source': 'NIST'},  # H3NO ΔHf=-43.1
    'SiH2Cl2': {'smiles': 'Cl[SiH2]Cl', 'D_at': 15.019, 'source': 'NIST'},  # Cl2H2Si ΔHf=-320.5
    'SiHCl3': {'smiles': 'Cl[SiH](Cl)Cl', 'D_at': 15.838, 'source': 'NIST'},  # Cl3HSi ΔHf=-496.2
    'difluorobromomethane': {'smiles': 'FC(F)Br', 'D_at': 16.887, 'source': 'NIST'},  # CHBrF2 ΔHf=-424.0
    'SiH2F2': {'smiles': 'F[SiH2]F', 'D_at': 17.244, 'source': 'NIST'},  # F2H2Si ΔHf=-619.0
    'N2O4': {'smiles': 'O=[N+]([O-])[N+](=O)[O-]', 'D_at': 20.013, 'source': 'NIST'},  # N2O4 ΔHf=11.1
    'cyanamide': {'smiles': 'NC#N', 'D_at': 20.287, 'source': 'NIST'},  # CH2N2 ΔHf=140.6
    '1,1,2-trichloroethane': {'smiles': 'ClCC(Cl)Cl', 'D_at': 26.877, 'source': 'NIST'},  # C2H3Cl3 ΔHf=-142.0
    'iodoethane': {'smiles': 'CCI', 'D_at': 27.343, 'source': 'NIST'},  # C2H5I ΔHf=-8.1
    'methyl_thiocyanate': {'smiles': 'CSC#N', 'D_at': 28.053, 'source': 'NIST'},  # C2H3NS ΔHf=130.5
    'HCFC_141b': {'smiles': 'CC(F)(Cl)Cl', 'D_at': 28.484, 'source': 'NIST'},  # C2H3Cl2F ΔHf=-338.9
    '1,2-difluoroethane': {'smiles': 'FCCF', 'D_at': 30.161, 'source': 'NIST'},  # C2H4F2 ΔHf=-446.0
    'H3BO3': {'smiles': 'OB(O)O', 'D_at': 30.666, 'source': 'NIST'},  # BH3O3 ΔHf=-992.3
    'HFC_152a': {'smiles': 'CC(F)F', 'D_at': 30.690, 'source': 'NIST'},  # C2H4F2 ΔHf=-497.0
    'thioacetic_acid': {'smiles': 'CC(=O)S', 'D_at': 31.162, 'source': 'NIST'},  # C2H4OS ΔHf=-175.0
    'HFC_134a': {'smiles': 'FCC(F)(F)F', 'D_at': 31.864, 'source': 'NIST'},  # C2H2F4 ΔHf=-887.5
    'glyoxylic_acid': {'smiles': 'OC(=O)C=O', 'D_at': 32.025, 'source': 'NIST'},  # C2H2O3 ΔHf=-473.0
    'pentafluoroethane': {'smiles': 'FC(F)C(F)(F)F', 'D_at': 32.671, 'source': 'NIST'},  # C2HF5 ΔHf=-1104.0
    'dimethyl_disulfide': {'smiles': 'CSSC', 'D_at': 34.408, 'source': 'NIST'},  # C2H6S2 ΔHf=-24.2
    'allyl_chloride': {'smiles': 'C=CCCl', 'D_at': 34.886, 'source': 'NIST'},  # C3H5Cl ΔHf=-4.6
    '1,2,4-triazole': {'smiles': 'C1=NNC=N1', 'D_at': 35.201, 'source': 'NIST'},  # C2H3N3 ΔHf=109.0
    'thiazole': {'smiles': 'C1=CSC=N1', 'D_at': 35.511, 'source': 'NIST'},  # C3H3NS ΔHf=127.6
    'isoxazole': {'smiles': 'C1=NOC=C1', 'D_at': 35.729, 'source': 'NIST'},  # C3H3NO ΔHf=78.6
    'trifluoroacetic_acid': {'smiles': 'OC(=O)C(F)(F)F', 'D_at': 35.837, 'source': 'NIST'},  # C2HF3O2 ΔHf=-1069.9
    'oxazole': {'smiles': 'C1=COC=N1', 'D_at': 36.704, 'source': 'NIST'},  # C3H3NO ΔHf=-15.5
    'epichlorohydrin': {'smiles': 'ClCC1CO1', 'D_at': 38.959, 'source': 'NIST'},  # C3H5ClO ΔHf=-148.4
    'beta_propiolactone': {'smiles': 'C1CC(=O)O1', 'D_at': 39.409, 'source': 'NIST'},  # C3H4O2 ΔHf=-282.0
    '1-iodopropane': {'smiles': 'CCCI', 'D_at': 39.517, 'source': 'NIST'},  # C3H7I ΔHf=-30.0
    'pyrazole': {'smiles': 'C1=CNN=C1', 'D_at': 40.027, 'source': 'NIST'},  # C3H4N2 ΔHf=105.4
    '1-bromopropane': {'smiles': 'CCCBr', 'D_at': 40.161, 'source': 'NIST'},  # C3H7Br ΔHf=-87.0
    'ethanolamine': {'smiles': 'NCCO', 'D_at': 40.216, 'source': 'NIST'},  # C2H7NO ΔHf=-199.0
    '2-bromopropane': {'smiles': 'CC(Br)C', 'D_at': 40.289, 'source': 'NIST'},  # C3H7Br ΔHf=-99.4
    '1-chloropropane': {'smiles': 'CCCCl', 'D_at': 40.724, 'source': 'NIST'},  # C3H7Cl ΔHf=-131.9
    '2-chloropropane': {'smiles': 'CC(Cl)C', 'D_at': 40.858, 'source': 'NIST'},  # C3H7Cl ΔHf=-144.9
    '1,3,5-triazine': {'smiles': 'C1=NC=NC=N1', 'D_at': 41.417, 'source': 'NIST'},  # C3H3N3 ΔHf=226.0
    '1,1,1-trifluoroacetone': {'smiles': 'CC(=O)C(F)(F)F', 'D_at': 42.632, 'source': 'NIST'},  # C3H3F3O ΔHf=-822.0
    'pyruvic_acid': {'smiles': 'CC(=O)C(=O)O', 'D_at': 43.049, 'source': 'NIST'},  # C3H4O3 ΔHf=-384.0
    'propanethiol': {'smiles': 'CCCS', 'D_at': 43.930, 'source': 'NIST'},  # C3H8S ΔHf=-67.4
    'methacrylonitrile': {'smiles': 'CC(=C)C#N', 'D_at': 44.995, 'source': 'NIST'},  # C4H5N ΔHf=88.0
    'ethylene_carbonate': {'smiles': 'C1COC(=O)O1', 'D_at': 45.142, 'source': 'NIST'},  # C3H4O3 ΔHf=-586.0
    'pyridazine': {'smiles': 'C1=CC=NN=C1', 'D_at': 45.663, 'source': 'NIST'},  # C4H4N2 ΔHf=278.3
    'maleic_anhydride': {'smiles': 'O=C1OC(=O)C=C1', 'D_at': 46.290, 'source': 'NIST'},  # C4H2O3 ΔHf=-416.0
    'methyl_vinyl_ketone': {'smiles': 'C=CC(=O)C', 'D_at': 46.887, 'source': 'NIST'},  # C4H6O ΔHf=-100.0
    'perfluoropropane': {'smiles': 'FC(F)(F)C(F)(F)C(F)(F)F', 'D_at': 47.345, 'source': 'NIST'},  # C3F8 ΔHf=-1783.0
    'propionamide': {'smiles': 'CCC(=O)N', 'D_at': 48.224, 'source': 'NIST'},  # C3H7NO ΔHf=-255.0
    'isopropylamine': {'smiles': 'CC(C)N', 'D_at': 48.385, 'source': 'NIST'},  # C3H9N ΔHf=-83.7
    'trioxane': {'smiles': 'C1OCOCO1', 'D_at': 48.412, 'source': 'NIST'},  # C3H6O3 ΔHf=-465.5
    'maleimide': {'smiles': 'O=C1C=CC(=O)N1', 'D_at': 48.938, 'source': 'NIST'},  # C4H3NO2 ΔHf=-230.0
    'dimethoxymethane': {'smiles': 'COCOC', 'D_at': 49.136, 'source': 'NIST'},  # C3H8O2 ΔHf=-348.5
    'cyclopentadiene': {'smiles': 'C1C=CC=C1', 'D_at': 49.304, 'source': 'NIST'},  # C5H6 ΔHf=134.3
    '1,3-propanediol': {'smiles': 'OCCCO', 'D_at': 49.757, 'source': 'NIST'},  # C3H8O2 ΔHf=-408.4
    '1,2-propanediol': {'smiles': 'CC(O)CO', 'D_at': 49.890, 'source': 'NIST'},  # C3H8O2 ΔHf=-421.3
    'trimethylborane': {'smiles': 'CB(C)C', 'D_at': 49.957, 'source': 'NIST'},  # C3H9B ΔHf=-143.1
    '1,2-epoxybutane': {'smiles': 'CCC1CO1', 'D_at': 51.323, 'source': 'NIST'},  # C4H8O ΔHf=-92.0
    'biuret': {'smiles': 'NC(=O)NC(=O)N', 'D_at': 51.641, 'source': 'NIST'},  # C2H5N3O2 ΔHf=-542.8
    'thiophene_2_carboxaldehyde': {'smiles': 'O=CC1=CC=CS1', 'D_at': 51.726, 'source': 'NIST'},  # C5H4OS ΔHf=-9.0
    'diacetyl': {'smiles': 'CC(=O)C(=O)C', 'D_at': 51.804, 'source': 'NIST'},  # C4H6O2 ΔHf=-325.2
    'succinic_anhydride': {'smiles': 'O=C1OC(=O)CC1', 'D_at': 51.962, 'source': 'NIST'},  # C4H4O3 ΔHf=-527.3
    'crotonic_acid': {'smiles': 'CC=CC(=O)O', 'D_at': 51.967, 'source': 'NIST'},  # C4H6O2 ΔHf=-341.0
    '2-methylimidazole': {'smiles': 'CC1=NC=CN1', 'D_at': 52.237, 'source': 'NIST'},  # C4H6N2 ΔHf=80.0
    'perfluorocyclobutane': {'smiles': 'FC1(F)C(F)(F)C(F)(F)C1(F)F', 'D_at': 52.282, 'source': 'NIST'},  # C4F8 ΔHf=-1542.7
    '1-amino-2-propanol': {'smiles': 'CC(O)CN', 'D_at': 52.463, 'source': 'NIST'},  # C3H9NO ΔHf=-228.0
    'alanine': {'smiles': 'CC(N)C(=O)O', 'D_at': 52.558, 'source': 'NIST'},  # C3H7NO2 ΔHf=-424.0
    'furfural': {'smiles': 'O=CC1=CC=CO1', 'D_at': 52.907, 'source': 'NIST'},  # C5H4O2 ΔHf=-151.0
    'spiropentane': {'smiles': 'C1CC11CC1', 'D_at': 53.295, 'source': 'NIST'},  # C5H8 ΔHf=185.2
    'methyl_cyanoacetate': {'smiles': 'COC(=O)CC#N', 'D_at': 53.612, 'source': 'NIST'},  # C4H5NO2 ΔHf=-245.0
    'glycerol': {'smiles': 'OCC(O)CO', 'D_at': 54.096, 'source': 'NIST'},  # C3H8O3 ΔHf=-577.9
    'pyridine_N-oxide': {'smiles': '[O-][n+]1ccccc1', 'D_at': 54.850, 'source': 'NIST'},  # C5H5NO ΔHf=103.0
    'succinimide': {'smiles': 'O=C1CCC(=O)N1', 'D_at': 54.965, 'source': 'NIST'},  # C4H5NO2 ΔHf=-375.5
    'iodobenzene': {'smiles': 'IC1=CC=CC=C1', 'D_at': 55.262, 'source': 'NIST'},  # C6H5I ΔHf=164.9
    '2-pyrrolidone': {'smiles': 'O=C1CCCN1', 'D_at': 55.445, 'source': 'NIST'},  # C4H7NO ΔHf=-235.0
    'N,N-dimethylurea': {'smiles': 'CN(C)C(=O)N', 'D_at': 55.859, 'source': 'NIST'},  # C3H8N2O ΔHf=-301.0
    'dimethylurea': {'smiles': 'CNC(=O)NC', 'D_at': 55.974, 'source': 'NIST'},  # C3H8N2O ΔHf=-312.1
    'propylene_carbonate': {'smiles': 'CC1COC(=O)O1', 'D_at': 57.371, 'source': 'NIST'},  # C4H6O3 ΔHf=-613.2
    'diallyl_sulfide': {'smiles': 'C=CCSC=C', 'D_at': 57.802, 'source': 'NIST'},  # C5H8S ΔHf=27.5
    'isobutanol': {'smiles': 'CC(C)CO', 'D_at': 57.830, 'source': 'NIST'},  # C4H10O ΔHf=-283.8
    'diketene': {'smiles': 'C=CC(=O)OC=C', 'D_at': 57.934, 'source': 'NIST'},  # C5H6O2 ΔHf=-200.0
    'isobutyric_acid': {'smiles': 'CC(C)C(=O)O', 'D_at': 57.968, 'source': 'NIST'},  # C4H8O2 ΔHf=-484.0
    'furfuryl_alcohol': {'smiles': 'OCC1=CC=CO1', 'D_at': 58.056, 'source': 'NIST'},  # C5H6O2 ΔHf=-211.8
    'cytosine': {'smiles': 'NC1=NC(=O)NC=C1', 'D_at': 58.898, 'source': 'NIST'},  # C4H5N3O ΔHf=-58.8
    'cyclopentanone': {'smiles': 'O=C1CCCC1', 'D_at': 59.788, 'source': 'NIST'},  # C5H8O ΔHf=-192.1
    'diethyl_sulfoxide': {'smiles': 'CCS(=O)CC', 'D_at': 59.885, 'source': 'NIST'},  # C4H10OS ΔHf=-205.0
    'sec-butylamine': {'smiles': 'CCC(C)N', 'D_at': 60.548, 'source': 'NIST'},  # C4H11N ΔHf=-104.6
    'sulfolane': {'smiles': 'C1CCS(=O)(=O)C1', 'D_at': 60.711, 'source': 'NIST'},  # C4H8O2S ΔHf=-471.5
    'tert-butylamine': {'smiles': 'CC(C)(C)N', 'D_at': 60.717, 'source': 'NIST'},  # C4H11N ΔHf=-120.9
    'nitrosobenzene': {'smiles': 'O=NC1=CC=CC=C1', 'D_at': 61.169, 'source': 'NIST'},  # C6H5NO ΔHf=210.0
    'acetaldehyde_dimethyl_acetal': {'smiles': 'CC(OC)OC', 'D_at': 61.510, 'source': 'NIST'},  # C4H10O2 ΔHf=-389.7
    '1,4-cyclohexadiene': {'smiles': 'C1C=CCC=C1', 'D_at': 61.565, 'source': 'NIST'},  # C6H8 ΔHf=104.0
    'trimethyl_phosphite': {'smiles': 'COP(OC)OC', 'D_at': 61.575, 'source': 'NIST'},  # C3H9O3P ΔHf=-765.0
    'barbituric_acid': {'smiles': 'O=C1CC(=O)NC(=O)N1', 'D_at': 61.892, 'source': 'NIST'},  # C4H4N2O3 ΔHf=-540.0
    '1,4-butanediol': {'smiles': 'OCCCCO', 'D_at': 61.893, 'source': 'NIST'},  # C4H10O2 ΔHf=-426.7
    '2-methyl-1,3-propanediol': {'smiles': 'OCC(C)CO', 'D_at': 62.043, 'source': 'NIST'},  # C4H10O2 ΔHf=-441.2
    'valeronitrile': {'smiles': 'CCCCC#N', 'D_at': 62.269, 'source': 'NIST'},  # C5H9N ΔHf=10.0
    'dimethyl_methylphosphonate': {'smiles': 'CP(=O)(OC)OC', 'D_at': 62.663, 'source': 'NIST'},  # C3H9O3P ΔHf=-870.0
    'methyl_methacrylate': {'smiles': 'COC(=O)C(=C)C', 'D_at': 64.028, 'source': 'NIST'},  # C5H8O2 ΔHf=-352.0
    'ethyl_acrylate': {'smiles': 'CCOC(=O)C=C', 'D_at': 64.049, 'source': 'NIST'},  # C5H8O2 ΔHf=-354.0
    'acetylacetone': {'smiles': 'CC(=O)CC(=O)C', 'D_at': 64.327, 'source': 'NIST'},  # C5H8O2 ΔHf=-380.8
    'delta_valerolactone': {'smiles': 'O=C1CCCCO1', 'D_at': 64.349, 'source': 'NIST'},  # C5H8O2 ΔHf=-383.0
    '2-methyltetrahydrofuran': {'smiles': 'CC1CCCO1', 'D_at': 64.653, 'source': 'NIST'},  # C5H10O ΔHf=-225.5
    'cyclopentanol': {'smiles': 'OC1CCCC1', 'D_at': 64.824, 'source': 'NIST'},  # C5H10O ΔHf=-242.0
    'methyl_isopropyl_ketone': {'smiles': 'CC(C)C(=O)C', 'D_at': 65.038, 'source': 'NIST'},  # C5H10O ΔHf=-262.6
    'resorcinol': {'smiles': 'OC1=CC(=CC=C1)O', 'D_at': 66.149, 'source': 'NIST'},  # C6H6O2 ΔHf=-276.0
    'trimethyl_borate': {'smiles': 'COB(OC)OC', 'D_at': 66.651, 'source': 'NIST'},  # C3H9BO3 ΔHf=-1006.3
    'NMP': {'smiles': 'CN1CCCC1=O', 'D_at': 67.671, 'source': 'NIST'},  # C5H9NO ΔHf=-262.0
    '2-aminophenol': {'smiles': 'NC1=CC=CC=C1O', 'D_at': 68.549, 'source': 'NIST'},  # C6H7NO ΔHf=-66.0
    '4-aminophenol': {'smiles': 'NC1=CC=C(O)C=C1', 'D_at': 68.559, 'source': 'NIST'},  # C6H7NO ΔHf=-67.0
    'benzyl_chloride': {'smiles': 'ClCC1=CC=CC=C1', 'D_at': 69.037, 'source': 'NIST'},  # C7H7Cl ΔHf=3.0
    '2-chlorotoluene': {'smiles': 'CC1=CC=CC=C1Cl', 'D_at': 69.047, 'source': 'NIST'},  # C7H7Cl ΔHf=2.0
    'tetrahydrofurfuryl_alcohol': {'smiles': 'OCC1CCCO1', 'D_at': 69.414, 'source': 'NIST'},  # C5H10O2 ΔHf=-435.7
    'methyl_butyrate': {'smiles': 'CCCC(=O)OC', 'D_at': 69.625, 'source': 'NIST'},  # C5H10O2 ΔHf=-456.0
    'diethanolamine': {'smiles': 'OCCNCCO', 'D_at': 69.718, 'source': 'NIST'},  # C4H11NO2 ΔHf=-491.0
    'phenylacetylene': {'smiles': 'C#CC1=CC=CC=C1', 'D_at': 69.802, 'source': 'NIST'},  # C8H6 ΔHf=306.6
    'isopropyl_acetate': {'smiles': 'CC(C)OC(=O)C', 'D_at': 69.887, 'source': 'NIST'},  # C5H10O2 ΔHf=-481.3
    'trimethylacetic_acid': {'smiles': 'CC(C)(C)C(=O)O', 'D_at': 69.990, 'source': 'NIST'},  # C5H10O2 ΔHf=-491.2
    'valeric_acid': {'smiles': 'CCCCC(=O)O', 'D_at': 69.997, 'source': 'NIST'},  # C5H10O2 ΔHf=-491.9
    'ethyl_propanoate': {'smiles': 'CCOC(=O)CC', 'D_at': 70.109, 'source': 'NIST'},  # C5H10O2 ΔHf=-502.7
    '4-fluorotoluene': {'smiles': 'CC1=CC=C(F)C=C1', 'D_at': 70.403, 'source': 'NIST'},  # C7H7F ΔHf=-170.7
    'phenyl_isocyanate': {'smiles': 'O=C=NC1=CC=CC=C1', 'D_at': 71.344, 'source': 'NIST'},  # C7H5NO ΔHf=-55.0
    'N-methylmorpholine': {'smiles': 'CN1CCOCC1', 'D_at': 71.464, 'source': 'NIST'},  # C5H11NO ΔHf=-192.0
    'adiponitrile': {'smiles': 'N#CCCCCC#N', 'D_at': 71.555, 'source': 'NIST'},  # C6H8N2 ΔHf=85.4
    'mesityl_oxide': {'smiles': 'CC(=CC(=O)C)C', 'D_at': 71.625, 'source': 'NIST'},  # C6H10O ΔHf=-181.5
    'N,N-diethylformamide': {'smiles': 'CCN(CC)C=O', 'D_at': 71.951, 'source': 'NIST'},  # C5H11NO ΔHf=-239.0
    'salicylaldehyde': {'smiles': 'OC1=CC=CC=C1C=O', 'D_at': 72.220, 'source': 'NIST'},  # C7H6O2 ΔHf=-145.0
    'benzimidazole': {'smiles': 'C1=CC=C2C(=C1)N=CN2', 'D_at': 73.468, 'source': 'NIST'},  # C7H6N2 ΔHf=181.5
    'norbornene': {'smiles': 'C1CC2CC1C=C2', 'D_at': 73.735, 'source': 'NIST'},  # C7H10 ΔHf=82.4
    'cresol_o': {'smiles': 'CC1=CC=CC=C1O', 'D_at': 73.986, 'source': 'NIST'},  # C7H8O ΔHf=-128.6
    'cresol_m': {'smiles': 'CC1=CC(=CC=C1)O', 'D_at': 74.024, 'source': 'NIST'},  # C7H8O ΔHf=-132.3
    '2,6-dimethylpyridine': {'smiles': 'CC1=CC=CC(=N1)C', 'D_at': 76.620, 'source': 'NIST'},  # C7H9N ΔHf=58.7
    'guaiacol': {'smiles': 'COC1=CC=CC=C1O', 'D_at': 77.378, 'source': 'NIST'},  # C7H8O2 ΔHf=-206.7
    '2-nitrotoluene': {'smiles': 'CC1=CC=CC=C1[N+](=O)[O-]', 'D_at': 77.407, 'source': 'NIST'},  # C7H7NO2 ΔHf=45.2
    '4-nitrotoluene': {'smiles': 'CC1=CC=C(C=C1)[N+](=O)[O-]', 'D_at': 77.554, 'source': 'NIST'},  # C7H7NO2 ΔHf=31.0
    '3-nitrotoluene': {'smiles': 'CC1=CC(=CC=C1)[N+](=O)[O-]', 'D_at': 77.613, 'source': 'NIST'},  # C7H7NO2 ΔHf=25.3
    'indole': {'smiles': 'C1=CC=C2C(=C1)C=CN2', 'D_at': 78.208, 'source': 'NIST'},  # C8H7N ΔHf=186.2
    'salicylic_acid': {'smiles': 'OC1=CC=CC=C1C(=O)O', 'D_at': 78.428, 'source': 'NIST'},  # C7H6O3 ΔHf=-494.8
    'styrene_oxide': {'smiles': 'C1(CO1)C2=CC=CC=C2', 'D_at': 79.843, 'source': 'NIST'},  # C8H8O ΔHf=23.0
    'cyclohexylamine': {'smiles': 'NC1CCCCC1', 'D_at': 79.917, 'source': 'NIST'},  # C6H13N ΔHf=-104.1
    'N-methylpiperidine': {'smiles': 'CN1CCCCC1', 'D_at': 80.131, 'source': 'NIST'},  # C6H13N ΔHf=-124.7
    'butyl_acetate': {'smiles': 'CCCCOC(=O)C', 'D_at': 81.875, 'source': 'NIST'},  # C6H12O2 ΔHf=-485.3
    'diisopropyl_ether': {'smiles': 'CC(C)OC(C)C', 'D_at': 82.090, 'source': 'NIST'},  # C6H14O ΔHf=-319.2
    'diethyl_oxalate': {'smiles': 'CCOC(=O)C(=O)OCC', 'D_at': 85.182, 'source': 'NIST'},  # C6H10O4 ΔHf=-742.0
    '2-phenylethanol': {'smiles': 'OCCC1=CC=CC=C1', 'D_at': 85.865, 'source': 'NIST'},  # C8H10O ΔHf=-122.1
    'acetal': {'smiles': 'CCOC(OCC)C', 'D_at': 86.028, 'source': 'NIST'},  # C6H14O2 ΔHf=-450.0
    'paraldehyde': {'smiles': 'CC1OC(C)OC(C)O1', 'D_at': 86.095, 'source': 'NIST'},  # C6H12O3 ΔHf=-643.3
    'triethylborane': {'smiles': 'CCB(CC)CC', 'D_at': 86.331, 'source': 'NIST'},  # C6H15B ΔHf=-194.6
    'pinacol': {'smiles': 'CC(O)(C)C(O)(C)C', 'D_at': 86.453, 'source': 'NIST'},  # C6H14O2 ΔHf=-491.0
    'N,N-dimethylaniline': {'smiles': 'CN(C)C1=CC=CC=C1', 'D_at': 88.134, 'source': 'NIST'},  # C8H11N ΔHf=100.5
    'N-ethylaniline': {'smiles': 'CCNC1=CC=CC=C1', 'D_at': 88.605, 'source': 'NIST'},  # C8H11N ΔHf=55.0
    'methyl_salicylate': {'smiles': 'COC(=O)C1=CC=CC=C1O', 'D_at': 89.770, 'source': 'NIST'},  # C8H8O3 ΔHf=-436.5
    '3-ethylpentane': {'smiles': 'CCC(CC)CC', 'D_at': 90.110, 'source': 'NIST'},  # C7H16 ΔHf=-189.5
    '3-methylhexane': {'smiles': 'CCCC(C)CC', 'D_at': 90.128, 'source': 'NIST'},  # C7H16 ΔHf=-191.3
    '2,3-dimethylpentane': {'smiles': 'CC(C)C(C)CC', 'D_at': 90.157, 'source': 'NIST'},  # C7H16 ΔHf=-194.1
    '2-methylhexane': {'smiles': 'CCCCC(C)C', 'D_at': 90.162, 'source': 'NIST'},  # C7H16 ΔHf=-194.6
    '3,3-dimethylpentane': {'smiles': 'CCC(C)(C)CC', 'D_at': 90.231, 'source': 'NIST'},  # C7H16 ΔHf=-201.2
    '2,4-dimethylpentane': {'smiles': 'CC(C)CC(C)C', 'D_at': 90.236, 'source': 'NIST'},  # C7H16 ΔHf=-201.7
    '2,2,3-trimethylbutane': {'smiles': 'CC(C)C(C)(C)C', 'D_at': 90.264, 'source': 'NIST'},  # C7H16 ΔHf=-204.4
    'triethyl_phosphite': {'smiles': 'CCOP(OCC)OCC', 'D_at': 98.358, 'source': 'NIST'},  # C6H15O3P ΔHf=-856.0
    'acenaphthylene': {'smiles': 'C1=CC2=C3C(=C1)C=CC3=CC=C2', 'D_at': 104.505, 'source': 'NIST'},  # C12H8 ΔHf=261.0
    'hexamethyldisiloxane': {'smiles': 'C[Si](C)(C)O[Si](C)(C)C', 'D_at': 105.200, 'source': 'NIST'},  # C6H18OSi2 ΔHf=-777.0
    '2-ethylhexanol': {'smiles': 'CCCCC(CC)CO', 'D_at': 106.460, 'source': 'NIST'},  # C8H18O ΔHf=-365.2
    'di-n-butylamine': {'smiles': 'CCCCNCCCC', 'D_at': 108.874, 'source': 'NIST'},  # C8H19N ΔHf=-156.6
    'acenaphthene': {'smiles': 'C1CC2=CC=CC3=C2C1=CC=C3', 'D_at': 110.112, 'source': 'NIST'},  # C12H10 ΔHf=156.0
    'adamantane': {'smiles': 'C1C2CC3CC1CC(C2)C3', 'D_at': 111.824, 'source': 'NIST'},  # C10H16 ΔHf=-134.6
    'phenanthrene': {'smiles': 'C1=CC2=C3C=CC=CC3=CC2=CC=1', 'D_at': 112.538, 'source': 'NIST'},  # C13H8 ΔHf=202.6
    '12-crown-4': {'smiles': 'C1COCCOCCOCCO1', 'D_at': 113.739, 'source': 'NIST'},  # C8H16O4 ΔHf=-756.0
    'fluorene': {'smiles': 'C1=CC=C2C(=C1)CC3=CC=CC=C32', 'D_at': 117.312, 'source': 'NIST'},  # C13H10 ΔHf=178.0
    'anthracene': {'smiles': 'C1=CC2=CC3=CC=CC=C3C=C2C=C1', 'D_at': 124.191, 'source': 'NIST'},  # C14H10 ΔHf=230.9
    # ── N-heterocyclic expansion (NIST 298K, Apr 2026) ──────────────
    # Aminopyridines (C5H6N2, n=7, 1 ring)
    '2-aminopyridine': {'smiles': 'Nc1ccccn1', 'D_at': 59.270, 'source': 'NIST'},  # ΔHf=118.1 ±1.1
    '3-aminopyridine': {'smiles': 'Nc1cccnc1', 'D_at': 58.999, 'source': 'NIST'},  # ΔHf=144.2 ±1.6
    '4-aminopyridine': {'smiles': 'Nc1ccncc1', 'D_at': 59.148, 'source': 'NIST'},  # ΔHf=129.9 ±1.4
    # Hydroxypyridines (C5H5NO, n=7, 1 ring)
    '3-hydroxypyridine': {'smiles': 'Oc1cccnc1', 'D_at': 56.371, 'source': 'NIST'},  # ΔHf=-43.7 ±1.7
    '4-hydroxypyridine': {'smiles': 'Oc1ccncc1', 'D_at': 56.232, 'source': 'NIST'},  # ΔHf=-30.3 ±5.3
    # Cyanopyridines (C6H4N2, n=8, 1 ring)
    '2-cyanopyridine': {'smiles': 'N#Cc1ccccn1', 'D_at': 60.494, 'source': 'NIST'},  # ΔHf=280.7 ±1.5
    '3-cyanopyridine': {'smiles': 'N#Cc1cccnc1', 'D_at': 60.523, 'source': 'NIST'},  # ΔHf=277.9 ±2.0
    '4-cyanopyridine': {'smiles': 'N#Cc1ccncc1', 'D_at': 60.465, 'source': 'NIST'},  # ΔHf=283.5 ±1.1
    # Nucleobases (n=8-9, 1 ring)
    'uracil': {'smiles': 'O=C1NC=CC(=O)N1', 'D_at': 56.854, 'source': 'NIST'},  # C4H4N2O2 ΔHf=-303.1 ±2.3
    'thymine': {'smiles': 'CC1=CNC(=O)NC1=O', 'D_at': 69.066, 'source': 'NIST'},  # C5H6N2O2 ΔHf=-328.7 ±4.3
    # Acetylpyridines (C7H7NO, n=9, 1 ring)
    '2-acetylpyridine': {'smiles': 'CC(=O)c1ccccn1', 'D_at': 75.920, 'source': 'NIST'},  # ΔHf=-60.5 ±0.3
    '3-acetylpyridine': {'smiles': 'CC(=O)c1cccnc1', 'D_at': 75.978, 'source': 'NIST'},  # ΔHf=-66.1 ±0.8
    '4-acetylpyridine': {'smiles': 'CC(=O)c1ccncc1', 'D_at': 75.982, 'source': 'NIST'},  # ΔHf=-66.5 ±0.9
    # Pyridine acid (C6H5NO2, n=9, 1 ring)
    'nicotinic_acid': {'smiles': 'OC(=O)c1cccnc1', 'D_at': 68.224, 'source': 'NIST'},  # ΔHf=-221.5 ±1.5
    # Bicyclic N-heterocycles (n=9-10, 2 rings)
    'indazole': {'smiles': 'c1ccc2[nH]ncc2c1', 'D_at': 72.831, 'source': 'NIST'},  # C7H6N2 ΔHf=243.0 ±1.3
    'benzoxazole': {'smiles': 'c1ccc2ocnc2c1', 'D_at': 70.306, 'source': 'NIST'},  # C7H5NO ΔHf=45.14 ±0.52
    'quinoxaline': {'smiles': 'c1ccc2nccnc2c1', 'D_at': 80.287, 'source': 'NIST'},  # C8H6N2 ΔHf=240.3 ±3.3
    'quinazoline': {'smiles': 'c1ccc2ncncc2c1', 'D_at': 80.258, 'source': 'NIST'},  # C8H6N2 ΔHf=243.1 ±2.7
    'phthalazine': {'smiles': 'c1ccc2cnncc2c1', 'D_at': 79.358, 'source': 'NIST'},  # C8H6N2 ΔHf=329.9 ±3.3
    # Small N-heterocycles (n=5-6, 1 ring)
    '1H-tetrazole': {'smiles': 'c1nn[nH]n1', 'D_at': 28.226, 'source': 'NIST'},  # CH2N4 ΔHf=320.0 ±3.0
    '2-azetidinone': {'smiles': 'O=C1CCN1', 'D_at': 42.057, 'source': 'NIST'},  # C3H5NO ΔHf=-96.0 ±0.9
    '1-methylimidazole': {'smiles': 'CN1C=CN=C1', 'D_at': 51.755, 'source': 'NIST'},  # C4H6N2 ΔHf=126.5 ±1.1
    # ── Milestone 700: 5 additional NIST molecules ──────────────────
    'formamide': {'smiles': 'C(=O)N', 'D_at': 23.615, 'source': 'NIST'},  # CH3NO ΔHf=-186.0
    'diethyl_ether': {'smiles': 'CCOCC', 'D_at': 57.501, 'source': 'NIST'},  # C4H10O ΔHf=-252.1
    'propionitrile': {'smiles': 'CCC#N', 'D_at': 37.946, 'source': 'NIST'},  # C3H5N ΔHf=51.5
    'tetrahydropyran': {'smiles': 'C1CCOCC1', 'D_at': 64.631, 'source': 'NIST'},  # C5H10O ΔHf=-223.4
    'acrylamide': {'smiles': 'C=CC(=O)N', 'D_at': 42.382, 'source': 'NIST'},  # C3H5NO ΔHf=-127.3
})
