"""DFT comparison panel — PTC vs B3LYP head-to-head on identical molecules.

Two regimes :
  * Full benchmark : 860 mol, B3LYP/6-31G* (ZPE Scott-Radom 0.9806)
  * 3-bin segmented: 536 mol n≤12, 3-way PTC/def2-TZVP/6-31G* (geom + ZPE
    recycled from the 6-31G* run)

Data file regenerated by scripts/regenerate_dft_comparison_data.py.
"""
import streamlit as st
import json
import os
from ptc_app.i18n import t


def _load_data():
    path = os.path.join(os.path.dirname(__file__), '..', 'dft_comparison_data.json')
    with open(path) as f:
        return json.load(f)


def _best_source_url(row: dict) -> str | None:
    """Pick the most authoritative source URL available for a molecule.

    The URL is chosen to land as close as possible to the **D_at value**
    on the destination page, not just on the compound overview.

    Priority chain :
      1. url_cccbdb (CCCBDB exp atomization energy page — 146 mol with CAS)
      2. NIST WebBook by CAS, with Mask matching compound type (when CAS present)
      3. NIST WebBook by name, with Mask matching compound type (others)

    NIST Mask values used :
      - 400 (hex) = Constants of diatomic molecules  (n_atoms == 2 → has D0)
      - 1   (hex) = Thermochemistry (heats of formation; D_at derived)

    PubChem-by-SMILES URLs (url_primary / url_pubchem) are AVOIDED because
    27 % of molecules have bracketed SMILES (e.g. [Sc]F, [Cu]Cl) which
    break PubChem's structure search ("Unable to standardize").
    """
    import urllib.parse
    if row.get("url_cccbdb"):
        return row["url_cccbdb"]
    n_atoms = row.get("n_atoms")
    mask = "400" if n_atoms == 2 else "1"
    cas = row.get("cas")
    if cas:
        return (
            f"https://webbook.nist.gov/cgi/cbook.cgi?"
            f"ID={urllib.parse.quote(str(cas))}&Mask={mask}&Units=SI"
        )
    name = row.get("name")
    if name:
        n = urllib.parse.quote(str(name))
        return (
            f"https://webbook.nist.gov/cgi/cbook.cgi?"
            f"Name={n}&Mask={mask}&Units=SI"
        )
    return None


_SOURCE_TIER_A = {"ATcT_0K", "ATcT"}
_SOURCE_TIER_B = {"NIST", "JANAF", "HH", "CRC", "Gurvich", "CCCBDB",
                  "NIST-derived", "CRC/Luo"}
_SOURCE_TIER_C = {"3dMLBE20", "Luo2007", "Morse2019", "Bao2021",
                  "Gong2014", "Casey1993", "Peterson1997"}


def _source_tier(source):
    if not source: return "?"
    if source in _SOURCE_TIER_A: return "A"
    if source in _SOURCE_TIER_B: return "B"
    if source in _SOURCE_TIER_C: return "C"
    return "?"

def _reliability_label(row: dict) -> str:
    """Combined CCCBDB + Burcat reliability badge."""
    cs = row.get("combined_status")
    diff = row.get("combined_best_diff")
    if cs == "ok_consensus":
        return f"🟢🟢 {abs(diff):.1f}%" if diff is not None else "🟢🟢"
    if cs == "ok_one_source":
        return f"🟢 {abs(diff):.1f}%" if diff is not None else "🟢"
    if cs == "one_source_fail":
        return f"🟡 {abs(diff):.1f}%" if diff is not None else "🟡"
    if cs == "single_fail":
        a = abs(diff) if diff is not None else 0
        if a < 5:   return f"🟠 {a:.1f}%"
        if a < 15:  return f"🟠 {a:.1f}%"
        return f"🔴 {a:.0f}%"
    if cs == "conflict":
        a = abs(diff) if diff is not None else 0
        return f"🔴 {a:.1f}%"
    if cs == "n/a":
        return f"⚪ {_source_tier(row.get('source'))}"
    # Fallback : single-source CCCBDB
    s = row.get("audit_status") or "n/a"
    diff = row.get("audit_diff_pct")
    if s in ("ok_<1%", "warn_1-2%"):
        return f"🟢 {abs(diff):.1f}%" if diff is not None else "🟢"
    if s == "fail_>2%":
        if diff is None:
            return "🟠 fail"
        a = abs(diff)
        if a < 5:   return f"🟡 {a:.1f}%"
        if a < 15:  return f"🟠 {a:.1f}%"
        return f"🔴 {a:.0f}%"
    return f"⚪ {_source_tier(row.get('source'))}"


def render_dft_tab():
    st.markdown(f"### {t('dft_title')}")

    data = _load_data()
    all_ptc = data['all_ptc']
    basis = data.get('basis', '6-31g*')

    # ── Filter to HEAD-TO-HEAD only (both PTC and B3LYP converged) ──
    both_all = [r for r in all_ptc if r.get('D_b3lyp') is not None]
    n_total = data['n_total']

    # Verified-core filter
    verified_only = st.checkbox(
        "Verified core uniquement (cross-validé <2 % CCCBDB)",
        value=False,
        help=(
            "Restreint aux molécules dont le D_exp est cross-validé à <2 % "
            "avec CCCBDB. Donne des stats headline plus serrées, perd ~30 "
            "TM-diatomics canoniques HH et les molécules non auto-vérifiables."
        ),
    )
    if verified_only:
        # Prefer combined status when available
        both = [r for r in both_all
                if r.get('combined_status') in ('ok_consensus', 'ok_one_source')
                or (r.get('combined_status') is None
                    and r.get('audit_status') in ('ok_<1%', 'warn_1-2%'))]
    else:
        both = both_all
    n_h2h = len(both)
    n_fail = n_total - len(both_all)

    n_unsupported = data.get('n_b3lyp_unsupported_basis', 0)
    n_scf_fail = data.get('n_b3lyp_scf_fail', 0)
    n_pathological = data.get('n_b3lyp_pathological', 0)

    if verified_only:
        st.caption(
            f"**Verified core** : {n_h2h} molécules cross-validées <2 % CCCBDB "
            f"où PTC ET B3LYP/{basis} convergent. Headline stats plus serrées."
        )
    else:
        st.caption(
            f"Comparaison équitable : **{n_h2h} molécules** où PTC ET B3LYP/{basis} "
            f"produisent un D_at exploitable (ZPE Scott-Radom 0.9806 appliqué). "
            f"Sur {n_total} du jeu de test : {n_unsupported} elements non supportés "
            f"par 6-31G* (Ag/Au/transition metals/I), {n_scf_fail} échecs SCF/Hessian, "
            f"{n_pathological} outliers pathologiques |err|>5 eV exclus. "
            f"Référence ATcT 0K. 0 paramètre PTC."
        )

    import pandas as pd
    import statistics

    # ── Compute stats on the overlap set ──
    ptc_errs = [abs(r['err_ptc']) for r in both]
    b3lyp_errs = [abs(r['err_b3lyp']) for r in both]
    ptc_wins = sum(1 for r in both if abs(r['err_ptc']) < abs(r['err_b3lyp']))
    b3lyp_wins = n_h2h - ptc_wins
    ptc_mae = statistics.mean(ptc_errs)
    b3lyp_mae = statistics.mean(b3lyp_errs)
    b3lyp_t = data.get('b3lyp_avg_time_s', 4.6)
    ptc_t = data.get('ptc_time_ms', 3) / 1000
    speedup = b3lyp_t / ptc_t if ptc_t > 0 else 0

    # ── Header metrics (head-to-head) ──
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Head-to-head", f"{n_h2h} mol")
    c2.metric("PTC gagne", f"{ptc_wins}/{n_h2h} ({100*ptc_wins/n_h2h:.0f}%)")
    c3.metric("PTC MAE", f"{ptc_mae:.2f}%")
    c4.metric(f"B3LYP MAE", f"{b3lyp_mae:.2f}%")

    st.divider()

    has_def2tzvp = data.get("def2tzvp_3way") is not None
    tab_labels = [
        "Scatter PTC vs B3LYP",
        "Top 30 écarts B3LYP",
        "Distribution erreurs",
        "Temps de calcul",
    ]
    if has_def2tzvp:
        tab_labels.append("3-voies def2-TZVP (n≤12)")

    tabs_all = st.tabs(tab_labels)
    tab_scatter, tab_table, tab_distrib, tab_timing = tabs_all[:4]
    tab_def2tzvp = tabs_all[4] if has_def2tzvp else None

    # ═══════════════════════════════════════════════════
    # TAB 1: Scatter — PTC vs Exp et B3LYP vs Exp
    # ═══════════════════════════════════════════════════
    with tab_scatter:
        import altair as alt

        st.markdown(f"#### {n_h2h} molecules — PTC vs Exp et B3LYP vs Exp")

        # Build DataFrame with both methods
        rows_scatter = []
        for r in both:
            rows_scatter.append({
                'D_exp': r['D_exp'],
                'D_calc': r['D_ptc'],
                'Methode': 'PTC (0 param)',
                'Molecule': r['name'],
                'Erreur (%)': r['err_ptc'],
            })
            rows_scatter.append({
                'D_exp': r['D_exp'],
                'D_calc': r['D_b3lyp'],
                'Methode': f'B3LYP/{basis}',
                'Molecule': r['name'],
                'Erreur (%)': r['err_b3lyp'],
            })

        df_scatter = pd.DataFrame(rows_scatter)
        max_val = max(df_scatter['D_exp'].max(), df_scatter['D_calc'].max()) * 1.05

        line = alt.Chart(pd.DataFrame({'x': [0, max_val], 'y': [0, max_val]})).mark_line(
            color='gray', strokeDash=[5, 5]
        ).encode(x='x:Q', y='y:Q')

        scatter = alt.Chart(df_scatter).mark_circle(size=20, opacity=0.5).encode(
            x=alt.X('D_exp:Q', title='D_at exp (eV)', scale=alt.Scale(domain=[0, max_val])),
            y=alt.Y('D_calc:Q', title='D_at calc (eV)', scale=alt.Scale(domain=[0, max_val])),
            color=alt.Color('Methode:N', scale=alt.Scale(
                domain=['PTC (0 param)', f'B3LYP/{basis}'],
                range=['#FF4B4B', '#4B8BFF']
            )),
            tooltip=['Molecule', 'D_exp', 'D_calc', 'Methode', 'Erreur (%)'],
        ).properties(height=500)

        st.altair_chart(line + scatter, use_container_width=True)

        st.caption(
            f"Rouge = PTC (MAE {ptc_mae:.2f}%), Bleu = B3LYP (MAE {b3lyp_mae:.2f}%). "
            f"Les points PTC sont plus proches de la diagonale (= meilleure precision)."
        )

    # ═══════════════════════════════════════════════════
    # TAB 2: Table head-to-head (top 30 worst B3LYP)
    # ═══════════════════════════════════════════════════
    with tab_table:
        st.markdown("#### Top 30 molécules où B3LYP a le plus d'erreur")
        st.caption(
            "Cliquez sur le lien pour ouvrir la fiche officielle de la valeur "
            "expérimentale (CCCBDB / NIST WebBook). "
            "Voir l'accordéon ci-dessous pour comprendre comment retrouver D_at sur "
            "chaque type de page."
        )

        with st.expander("Comment vérifier une valeur de D_at en cliquant sur un lien"):
            st.markdown(
                "**Aucune base ne publie D_at directement** — toutes publient "
                "l'enthalpie de formation ΔH_f. Les deux sont reliées par "
                "`D_at(M) = Σ ΔH_f(atomes) − ΔH_f(M)`. Selon la base sur laquelle on tombe :\n\n"
                "- **CCCBDB** (cccbdb.nist.gov) — page « Experimental data » qui "
                "  affiche ΔfH°(0K) directement, donc le calcul de D_at se réduit à "
                "  soustraire les ΔfH° atomiques. Liens activés quand notre base "
                "  contient un CAS validé.\n"
                "- **NIST WebBook** (webbook.nist.gov) — affiche ΔH_f de formation et, "
                "  pour les diatomiques, la « Constants of diatomic molecules » "
                "  Huber-Herzberg qui contient D₀ direct.\n"
                "- **PubChem** (pubchem.ncbi.nlm.nih.gov) — confirme l'identité de la "
                "  molécule (structure, formule)."
            )

        with st.expander("Code couleur de fiabilité — cross-check CCCBDB + Burcat"):
            st.markdown(
                "Chaque D_exp est cross-vérifié contre **deux** sources "
                "indépendantes : CCCBDB (NIST, dual-convention 0K/298K) et "
                "Burcat (Goos/Burcat/Ruscic, ~3000 espèces gas-phase).\n\n"
                "- 🟢🟢 **Both <2 %** : 310 mol (consensus, confiance maximale)\n"
                "- 🟢 **One <2 %, other n/a** : 236 mol\n"
                "- 🟡 **One <2 %, other >2 %** : 32 mol (drift de révision)\n"
                "- 🟠 **Single source >2 %** : 46 mol\n"
                "- 🔴 **Both >2 %** : 16 mol (vrai conflit)\n"
                "- ⚪ A/B/C **Aucune source** : 359 mol par tier\n\n"
                "**Total <2 %** : 546 mol (54.7 %).\n\n"
                "Détail : `benchmarkb3lyp/audit_combined_2026-05-04.csv`."
            )

        rows = []
        for r in sorted(both, key=lambda x: abs(x['err_b3lyp']), reverse=True)[:30]:
            winner = "PTC" if abs(r['err_ptc']) < abs(r['err_b3lyp']) else "B3LYP"
            rows.append({
                'Molécule': r['name'],
                'D_exp (eV)': float(r['D_exp']),
                'Fiabilité': _reliability_label(r),
                'Source': r.get('source') or '—',
                'Lien': _best_source_url(r) or '',
                'PTC err%': float(r['err_ptc']),
                'B3LYP err%': float(r['err_b3lyp']),
                'Gagnant': winner,
            })
        st.dataframe(
            pd.DataFrame(rows),
            use_container_width=True,
            hide_index=True,
            column_config={
                'D_exp (eV)':  st.column_config.NumberColumn(format="%.2f"),
                'PTC err%':    st.column_config.NumberColumn(format="%+.2f"),
                'B3LYP err%':  st.column_config.NumberColumn(format="%+.2f"),
                'Lien':        st.column_config.LinkColumn(
                    "Lien", display_text="↗ ouvrir",
                    help="Lien vers la référence expérimentale (CCCBDB, NIST, ou PubChem)",
                ),
            },
        )

    # ═══════════════════════════════════════════════════
    # TAB 3: Distribution des erreurs (head-to-head set)
    # ═══════════════════════════════════════════════════
    with tab_distrib:
        st.markdown(f"#### Distribution des erreurs — {n_h2h} molecules head-to-head")

        err_rows = []
        for r in both:
            err_rows.append({'Erreur (%)': r['err_ptc'], 'Methode': 'PTC'})
            err_rows.append({'Erreur (%)': r['err_b3lyp'], 'Methode': f'B3LYP/{basis}'})
        err_df = pd.DataFrame(err_rows)

        hist = alt.Chart(err_df).mark_bar(opacity=0.6).encode(
            x=alt.X('Erreur (%):Q', bin=alt.Bin(maxbins=60, extent=[-20, 20])),
            y='count()',
            color=alt.Color('Methode:N', scale=alt.Scale(
                domain=['PTC', f'B3LYP/{basis}'],
                range=['#FF4B4B', '#4B8BFF']
            )),
        ).properties(height=300)
        st.altair_chart(hist, use_container_width=True)

        # Stats table
        n_ptc_lt1 = sum(1 for e in ptc_errs if e < 1)
        n_ptc_lt2 = sum(1 for e in ptc_errs if e < 2)
        n_ptc_lt5 = sum(1 for e in ptc_errs if e < 5)
        n_ptc_gt10 = sum(1 for e in ptc_errs if e > 10)
        n_b_lt1 = sum(1 for e in b3lyp_errs if e < 1)
        n_b_lt2 = sum(1 for e in b3lyp_errs if e < 2)
        n_b_lt5 = sum(1 for e in b3lyp_errs if e < 5)
        n_b_gt10 = sum(1 for e in b3lyp_errs if e > 10)

        st.markdown(f"""
| Seuil | PTC | B3LYP/{basis} |
|-------|-----|---------------|
| < 1% | {n_ptc_lt1} ({n_ptc_lt1*100//n_h2h}%) | {n_b_lt1} ({n_b_lt1*100//n_h2h}%) |
| < 2% | {n_ptc_lt2} ({n_ptc_lt2*100//n_h2h}%) | {n_b_lt2} ({n_b_lt2*100//n_h2h}%) |
| < 5% | {n_ptc_lt5} ({n_ptc_lt5*100//n_h2h}%) | {n_b_lt5} ({n_b_lt5*100//n_h2h}%) |
| > 10% | {n_ptc_gt10} ({n_ptc_gt10*100//n_h2h}%) | {n_b_gt10} ({n_b_gt10*100//n_h2h}%) |
| **MAE** | **{ptc_mae:.2f}%** | {b3lyp_mae:.2f}% |
| Mediane | {statistics.median(ptc_errs):.2f}% | {statistics.median(b3lyp_errs):.2f}% |
| Max | {max(ptc_errs):.1f}% | {max(b3lyp_errs):.1f}% |
""")

    # ═══════════════════════════════════════════════════
    # TAB 4: Timing
    # ═══════════════════════════════════════════════════
    with tab_timing:
        st.markdown(f"#### Temps de calcul — {n_h2h} molecules")
        st.markdown(f"""
| Methode | Temps moyen | Parametres | MAE ({n_h2h} mol) | Echecs SCF |
|---------|-------------|------------|-------------------|------------|
| **PTC** | **{data['ptc_time_ms']:.0f} ms** | **0** | **{ptc_mae:.2f}%** | 0 |
| B3LYP/{basis} | {b3lyp_t:.1f}s | ~50 | {b3lyp_mae:.2f}% | {n_fail} ({n_fail*100//n_total}%) |

**PTC : {speedup:,.0f}x plus rapide, {b3lyp_mae/max(ptc_mae,0.01):.1f}x plus precis, 0 parametre, 0 echec.**
""")

    # ═══════════════════════════════════════════════════
    # TAB 5: 3-voies def2-TZVP
    # ═══════════════════════════════════════════════════
    if tab_def2tzvp is not None:
        with tab_def2tzvp:
            _render_def2tzvp_tab(data["def2tzvp_3way"])


def _render_def2tzvp_tab(tz):
    """Render the 3-way × 3-bin comparison panel (PTC vs def2-TZVP vs 6-31G*)."""
    import altair as alt
    import pandas as pd

    st.markdown("#### Comparaison 3-voies par bin de taille — 536 molécules (n≤12)")
    st.caption(
        "Test contre B3LYP/def2-TZVP (base moderne, single-point sur géom 6-31G\\* "
        "+ ZPE recyclée). 3 bins équilibrés : A=petites (n=2-4), B=moyennes (n=5-8), "
        "C=grandes (n=9-12). Couverture exhaustive dans chaque bin."
    )

    bin_order = ["A (n=2-4)", "B (n=5-8)", "C (n=9-12)", "A+B+C (n≤12)"]
    bins_data = tz["bins"]

    # ── Headline metrics on full set (A+B+C) ──
    full = bins_data.get("A+B+C (n≤12)") or list(bins_data.values())[-1]
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Head-to-head", f"{full['n']} mol")
    c2.metric("PTC MAE", f"{full['PTC']['mae_eV']:.3f} eV", f"{full['PTC']['mae_pct']:.2f}%")
    c3.metric("B3LYP/def2-TZVP MAE", f"{full['B3LYP_def2-TZVP']['mae_eV']:.3f} eV", f"{full['B3LYP_def2-TZVP']['mae_pct']:.2f}%")
    c4.metric("PTC win vs def2-TZVP", f"{full['head_to_head']['PTC_vs_def2TZVP_pct']:.0f}%")

    st.divider()

    # ── Bar chart : MAE par bin × méthode ──
    st.markdown("##### MAE par bin de taille (eV)")
    bar_rows = []
    for bn in bin_order:
        if bn not in bins_data:
            continue
        bd = bins_data[bn]
        bar_rows.append({"Bin": bn, "Methode": "PTC",              "MAE_eV": bd["PTC"]["mae_eV"]})
        bar_rows.append({"Bin": bn, "Methode": "B3LYP/def2-TZVP",  "MAE_eV": bd["B3LYP_def2-TZVP"]["mae_eV"]})
        bar_rows.append({"Bin": bn, "Methode": "B3LYP/6-31G*",     "MAE_eV": bd["B3LYP_6-31Gs"]["mae_eV"]})
    bar_df = pd.DataFrame(bar_rows)

    bar_chart = alt.Chart(bar_df).mark_bar().encode(
        x=alt.X("Bin:N", sort=bin_order, title=None),
        xOffset=alt.X("Methode:N"),
        y=alt.Y("MAE_eV:Q", title="MAE (eV)"),
        color=alt.Color("Methode:N", scale=alt.Scale(
            domain=["PTC", "B3LYP/def2-TZVP", "B3LYP/6-31G*"],
            range=["#FF4B4B", "#10b981", "#4B8BFF"],
        )),
        tooltip=["Bin", "Methode", alt.Tooltip("MAE_eV:Q", format=".3f")],
    ).properties(height=320)
    st.altair_chart(bar_chart, use_container_width=True)

    # ── 3 columns of bin metrics ──
    st.markdown("##### Détail par bin")
    cols = st.columns(3)
    for col, bn in zip(cols, ["A (n=2-4)", "B (n=5-8)", "C (n=9-12)"]):
        if bn not in bins_data:
            continue
        bd = bins_data[bn]
        with col:
            label = bn.split(" ")[0]
            st.markdown(f"**Bin {label}** — n = {bd['n']}")
            st.markdown(
                f"""
| | MAE eV | MAE % | <1 kcal | bias |
|---|---:|---:|---:|---:|
| **PTC** | **{bd['PTC']['mae_eV']:.3f}** | {bd['PTC']['mae_pct']:.2f}% | {bd['PTC']['within_1kcal']:.1f}% | {bd['PTC']['mean_signed']:+.2f} |
| def2-TZVP | {bd['B3LYP_def2-TZVP']['mae_eV']:.3f} | {bd['B3LYP_def2-TZVP']['mae_pct']:.2f}% | {bd['B3LYP_def2-TZVP']['within_1kcal']:.1f}% | {bd['B3LYP_def2-TZVP']['mean_signed']:+.2f} |
| 6-31G* | {bd['B3LYP_6-31Gs']['mae_eV']:.3f} | {bd['B3LYP_6-31Gs']['mae_pct']:.2f}% | {bd['B3LYP_6-31Gs']['within_1kcal']:.1f}% | {bd['B3LYP_6-31Gs']['mean_signed']:+.2f} |

PTC win vs def2-TZVP : **{bd['head_to_head']['PTC_vs_def2TZVP_pct']:.0f}%**
"""
            )

    st.divider()

    # ── Win rate par bin ──
    st.markdown("##### Win rate par bin (3-voies)")
    win_rows = []
    for bn in ["A (n=2-4)", "B (n=5-8)", "C (n=9-12)"]:
        if bn not in bins_data:
            continue
        bd = bins_data[bn]
        for method, key in [("PTC", "PTC"), ("def2-TZVP", "def2-TZVP"), ("6-31G*", "6-31Gs")]:
            win_rows.append({
                "Bin": bn,
                "Méthode": method,
                "Win rate (%)": bd["three_way_best_pct"][key],
            })
    win_df = pd.DataFrame(win_rows)
    win_chart = alt.Chart(win_df).mark_bar().encode(
        x=alt.X("Bin:N", sort=bin_order),
        y=alt.Y("Win rate (%):Q", stack="normalize"),
        color=alt.Color("Méthode:N", scale=alt.Scale(
            domain=["PTC", "def2-TZVP", "6-31G*"],
            range=["#FF4B4B", "#10b981", "#4B8BFF"],
        )),
        tooltip=["Bin", "Méthode", alt.Tooltip("Win rate (%):Q", format=".1f")],
    ).properties(height=260)
    st.altair_chart(win_chart, use_container_width=True)

    # ── Surprise Bin C ──
    bin_c = bins_data.get("C (n=9-12)")
    if bin_c:
        st.warning(
            f"**Régression def2-TZVP sur Bin C** : MAE def2-TZVP = "
            f"{bin_c['B3LYP_def2-TZVP']['mae_eV']:.2f} eV > 6-31G\\* "
            f"({bin_c['B3LYP_6-31Gs']['mae_eV']:.2f} eV) sur les molécules de 9-12 atomes. "
            f"Phénomène DFT connu : annulation d'erreur basis × fonctionnelle dans 6-31G\\* "
            f"qui disparaît avec def2-TZVP, exposant le défaut intrinsèque de la fonctionnelle B3LYP. "
            f"PTC reste meilleure ({bin_c['PTC']['mae_eV']:.2f} eV) et **non biaisée** "
            f"(biais signé {bin_c['PTC']['mean_signed']:+.2f} eV vs "
            f"{bin_c['B3LYP_def2-TZVP']['mean_signed']:+.2f} pour def2-TZVP)."
        )

    st.divider()

    # ── Speed comparison ──
    runtimes = tz.get("runtimes")
    if runtimes:
        st.markdown("##### Vitesse de calcul — PTC vs B3LYP/def2-TZVP")
        ptc_ms_overall = runtimes.get("ptc_per_mol_ms", 2.97)
        ptc_total_s = runtimes.get("ptc_total_s")
        measured_inline = runtimes.get("ptc_measured_inline", False)
        overall = runtimes.get("overall", {})
        per_bin = runtimes.get("per_bin", {})
        ref_m1 = runtimes.get("reference_m1_max")

        # Reference numbers on M1 Max (stable, doesn't drift between machines)
        if ref_m1:
            st.markdown(f"**Référence — {ref_m1['platform']} ({ref_m1['date']})**")
            ref_rows = []
            for bin_label, b in ref_m1["per_bin"].items():
                ref_rows.append({
                    "Sous-ensemble":         bin_label,
                    "n mol":                 b["n"],
                    "def2-TZVP total":       f"{b['def2tzvp_total_s']:.1f} s",
                    "def2-TZVP avg":         f"{b['def2tzvp_per_mol_s']:.2f} s/mol",
                    "PTC total":             f"{b['ptc_total_s']:.3f} s",
                    "PTC avg":               f"{b['ptc_per_mol_ms']:.2f} ms/mol",
                    "Ratio":                 f"× {b['speedup']:,.0f}".replace(",", " "),
                })
            st.dataframe(
                pd.DataFrame(ref_rows), use_container_width=True, hide_index=True,
            )
            st.caption(
                f"Mesures de référence sur {ref_m1['platform']}, conservées comme "
                f"baseline stable. Ratios mesurés directement, pas embellis."
            )
            st.divider()

        # Inline measurement on the current machine — supplementary info
        if overall and measured_inline and ptc_total_s:
            tot_s = overall.get("total_s", 0)
            avg_s = overall.get("per_mol_avg_s", 0)
            speedup_overall = (avg_s * 1000) / max(ptc_ms_overall, 1e-6)
            st.markdown(
                f"**Re-mesure inline (machine actuelle)** : PTC {ptc_total_s:.2f} s "
                f"pour 536 mol = {ptc_ms_overall:.2f} ms/mol → speedup overall "
                f"~{speedup_overall:,.0f}×. Le rapport varie entre machines mais "
                f"reste de l'ordre du millier sur petites mol et ~10⁴ sur grandes.".replace(",", " ")
            )
        elif overall:
            tot_s = overall.get("total_s", 0)
            avg_s = overall.get("per_mol_avg_s", 0)
            st.markdown(
                f"Le run def2-TZVP n≤12 (536 mol, single-point sans Hessien) a pris "
                f"{tot_s/60:.0f} min soit ~{avg_s:.1f} s/mol en moyenne."
            )

        # Per-bin speedup table — uses bin-specific PTC timings if measured
        if per_bin:
            speed_rows = []
            for bn in ["A (n=2-4)", "B (n=5-8)", "C (n=9-12)"]:
                if bn not in per_bin:
                    continue
                b = per_bin[bn]
                # Prefer per-bin PTC timing when measured inline; fall back
                # to the overall average otherwise.
                ptc_ms = b.get("ptc_per_mol_ms", ptc_ms_overall)
                speedup = b.get("speedup")
                if speedup is None:
                    speedup = (b["per_mol_avg_s"] * 1000) / max(ptc_ms, 1e-6)
                speed_rows.append({
                    "Bin": bn,
                    "n mol": b["n"],
                    "def2-TZVP avg (s/mol)": round(b["per_mol_avg_s"], 2),
                    "def2-TZVP max (s/mol)": round(b["per_mol_max_s"], 2),
                    "PTC avg (ms/mol)": round(ptc_ms, 2),
                    "PTC speedup": f"{speedup:,.0f} ×".replace(",", " "),
                })
            st.dataframe(
                pd.DataFrame(speed_rows),
                use_container_width=True,
                hide_index=True,
                column_config={
                    "def2-TZVP avg (s/mol)": st.column_config.NumberColumn(format="%.2f"),
                    "def2-TZVP max (s/mol)": st.column_config.NumberColumn(format="%.2f"),
                    "PTC avg (ms/mol)":      st.column_config.NumberColumn(format="%.2f"),
                },
            )
            st.caption(
                "Speedup croît avec la taille : SCF def2-TZVP scale en N⁴ "
                "(N = fonctions de base, ~30 par atome lourd), PTC reste à coût ~ms. "
                "Timing def2-TZVP single-point seulement (Hessien recyclé du run 6-31G\\*) ; "
                "avec Hessien complet à def2-TZVP, le speedup serait encore 5-20× plus grand."
            )

        # Bar chart speedup by bin
        if per_bin:
            speed_df = pd.DataFrame([
                {
                    "Bin": bn,
                    "Speedup": per_bin[bn].get(
                        "speedup",
                        (per_bin[bn]["per_mol_avg_s"] * 1000)
                        / max(per_bin[bn].get("ptc_per_mol_ms", ptc_ms_overall), 1e-6),
                    ),
                }
                for bn in ["A (n=2-4)", "B (n=5-8)", "C (n=9-12)"]
                if bn in per_bin
            ])
            speed_chart = alt.Chart(speed_df).mark_bar(color="#FF4B4B").encode(
                x=alt.X("Bin:N", sort=["A (n=2-4)", "B (n=5-8)", "C (n=9-12)"]),
                y=alt.Y("Speedup:Q", title="PTC speedup (×)"),
                tooltip=["Bin", alt.Tooltip("Speedup:Q", format=",.0f")],
            ).properties(height=240)
            st.altair_chart(speed_chart, use_container_width=True)

    st.divider()

    # ── Per-molecule table ──
    st.markdown("##### Détail par molécule (536)")
    mols = tz["molecules"]
    table_rows = []
    for m in mols:
        bin_label = "A" if m["n_atoms"] <= 4 else ("B" if m["n_atoms"] <= 8 else "C")
        errs = {
            "PTC": abs(m["err_ptc_eV"]),
            "def2-TZVP": abs(m["err_b3lyp_def2TZVP_eV"]),
            "6-31G*": abs(m["err_b3lyp_6-31Gs_eV"]),
        }
        winner = min(errs, key=errs.get)
        table_rows.append({
            "Nom": m["name"],
            "Bin": bin_label,
            "n_atoms": m["n_atoms"],
            "D_exp (eV)": m["D_exp"],
            "PTC err (eV)": m["err_ptc_eV"],
            "def2-TZVP err (eV)": m["err_b3lyp_def2TZVP_eV"],
            "6-31G* err (eV)": m["err_b3lyp_6-31Gs_eV"],
            "Gagnant": winner,
        })
    table_df = pd.DataFrame(table_rows)
    st.dataframe(
        table_df.sort_values("PTC err (eV)", key=lambda s: s.abs(), ascending=False),
        use_container_width=True,
        hide_index=True,
        column_config={
            "D_exp (eV)":       st.column_config.NumberColumn(format="%.2f"),
            "PTC err (eV)":     st.column_config.NumberColumn(format="%+.3f"),
            "def2-TZVP err (eV)": st.column_config.NumberColumn(format="%+.3f"),
            "6-31G* err (eV)":  st.column_config.NumberColumn(format="%+.3f"),
        },
    )
